### ISSUE TITLE
Start filtering "Bug" creat empty folder structure

### ISSUE THREAD

**Issue by Jan-Niklas-Tripp** [environmentalinformatics-marburg/distribution_digitizer_students#4]
It´s not really a Problem.

I forgot to use a "/" at the end of my path at the working directory. As i pushed the button "Start filtering" the app worked fine but i was woundering why i have no data. What happend was, the app created an empty folder structure like: "C:/folderpath/distribution_digitizer_students-maindata/output..".

Greetings,
Jan

**Comment by VenkateshMadhuvanthi** [comment]
You need to give the path. "C:/folderpath/distribution_digitizer_students-main" is not a path. ""C:/folderpath/distribution_digitizer_students-main/" is a path. Only when the path is correct, it can access the folders inside the path.
