### ISSUE TITLE
Classification does not work

### ISSUE THREAD

**Issue by Daniel269269** [environmentalinformatics-marburg/distribution_digitizer_students#6]
Hello :-)

For me, the template matching doesn't do anything. When I'm performing the map detection, there are maps being generated in the "classification/matching" folder right away (without hitting the "template matching" button. But these maps are exactly the same like the maps in the output folder and do not have any blue marks which were classified. When I hit "start template matching", it just says "successfully executed" in my R console but nothing happens and the maps still look the same (without blue marks). When I try to use filtering, it also says "successfully executed" but nothing happens at all and I do not even have a classification/filtering folder.

I have no clue how to fix this issue because I don't get an error message and I have specified symbols as templates so it should work actually.

Thank you for your help :-)
Daniel

**Comment by Daniel269269** [comment]
Ok, I fixed the issue and it was actually quite a stupid error... When creating the templates for the symbols I didn't add the .tif extension as I thought this would be default... Didn't encounter this problem when creating the templates for the maps.

But now I have a different question because I have quite a lot of maps which have a ton of overlapping occurrence data and I can't obtain a satisfactory classification. One map which makes problems is this one: 
![0062map_1_0_T8](https://user-images.githubusercontent.com/57835266/124843457-3d347780-df92-11eb-86ca-11b9cf117bee.png)

This was at a threshold of 0.8. Setting it to 0.7 yields this classification:
![0062map_1_0_T7](https://user-images.githubusercontent.com/57835266/124843510-5dfccd00-df92-11eb-96f1-a71db1f29ccb.png)

Then I tried to add more diverse templates and sampled more templates from the regions where points overlap  and the symbols are not as clean anymore, hoping that I can tell the software to classify those points as well. This is the result at Threshold=0.8
![0062map_1_0_T8_more_temp](https://user-images.githubusercontent.com/57835266/124843663-b16f1b00-df92-11eb-92dc-07b1a109e49d.png)

And this at 0.7:
![0062map_1_0_T07_more_templates](https://user-images.githubusercontent.com/57835266/124843681-bcc24680-df92-11eb-86bb-64146172d43c.png)

The last one is the best result I can get but a lot of points are still missing and it also sometimes classifies parts of the map which are no symbols. What should I do? Should I add more templates for those overlapping symbols? Because I already have quite a few of them. I also can't further decrease the threshold because it starts classifying junk. I have a few of those maps. My other maps which don't have overlapping symbols are working fine.

Thank you :-)
Daniel

**Comment by VenkateshMadhuvanthi** [comment]
Instead of cropping the whole circle, why don't you give the white center as the template?
![template_Eg](https://user-images.githubusercontent.com/70901714/125098646-7f1b0600-e0d7-11eb-98bc-e804e71c639d.PNG)

**Comment by VenkateshMadhuvanthi** [comment]
Yes. Probably, you need to upload files only with .tif. The goal is to extract as many points as possible. But then not the unwanted points. For example, for this image, try to increase the threshold value. 
![image](https://user-images.githubusercontent.com/70901714/125269853-64c86e80-e309-11eb-9f54-fc0f867e68b0.png)

**Comment by Daniel269269** [comment]
Alright, thank you :-) I think now I have a satisfactory output. But now I'm having trouble with the georeferencing.... It just doesn't do anything but I also don't get an error message. It just says "successfully executed" but I don't have any output. I don't even have a georeferencing folder. I'm having the same problem with filtering which also says successfully executed without generating any output. I did the georeferencing in QGIS and I'm having the .points file in the geopoints folder. Also, the .points file looks fine and is exactly like the one you showed during the course.

**Comment by VenkateshMadhuvanthi** [comment]
This might be because you might have given the wrong file path under the working directory in the DD Shiny application. Have a look at it once more and execute the modules again:):

**Comment by Daniel269269** [comment]
No my path is correct actually, because everything else works fine. So I can extract the maps and classify the symbols without problems and output is being generated but then (without changing the path or anything) the georeferencing and the filtering both doesn't do anything. I also double-checked this to be sure and when I specify the wrong path, my app crashes. But in my case with the correct path it doesn't crash or give me an error message. It just does not generate any output, which is very strange.

I just realized that I have a second folder called "../distribution_digitizer_students-maindata" and there a "/georeferencing" folder is being generated when I hit the georeferencing button. But this folder stays empty. When I delete this folder and hit georeferncing again, the app will create this folder again but without any data. This is also very strange because all my other output (like the map extraction or template matching) will be written in my main folder "../distribution_digitizer_students-main" and only the "/georeferncing" and "/filtering" folders are being created in the second folder "../distribution_digitizer_students-maindata" but both folders remain empty.

**Comment by VenkateshMadhuvanthi** [comment]
"I just realized that I have a second folder called "../distribution_digitizer_students-maindata" and there a "/georeferencing" folder is being generated when I hit the georeferencing button", This might be because you might not have given .points template or the output of filtering is empty. Why are there two folders?

**Comment by Daniel269269** [comment]
I have given a .points file but I don't have a filtering folder at all, that's true. This is because the filtering does not work as well and also doesn't do anything. To check if the georeferencing will work, I created an "output/classification/filtering" folder and copied the files from "output/classification/matching" to this folder. But the georeferencing still didn't work. I don't know why I have 2 folders. When I download the digitizer from github and extract it, it is only one folder. All my data will be stored in this folder. Only when I hit the filtering or georeferencing button, the second folder "../distribution_digitizer_students-maindata" will be created. This folder does not contain any data, it contains only 2 empty folders: "output/classification/filtering" and "output/georeferencing" it does not contain the app or any associated data, no input, no output, no anything. Just 2 empty folders for filtering and georeferncing. This folder is created any time I hit georeferencing or filtering. However, in my first folder where all the other data, input and output is contained, no filtering or georeferencing folder is created.

**Comment by VenkateshMadhuvanthi** [comment]
The georeferencing won't work if your input path directory is wrong. I guess your case is similar to Beza's case, you have too many folders and you opened start_dd_app.R from one and expecting the output in another folder.  Store your data/inputs and data/templates in a nice place. Delete all the repeating folders, do the step from the first again.  Do not confuse with too many folders. One path directory and One working directory will do the work :).

**Comment by Jan-Niklas-Tripp** [comment]
I had the same problem with "../distribution_digitizer_students-maindata" last week. It was a result of a missing "/" at the end of the path at 1.Set your working directory.

**Comment by Daniel269269** [comment]
Oh nooooo :D You are my hero!! I added a "/" and now it works perfectly.... Thank you! I wasted so much time on this and the past 3 days I tried to figure out what was going on and tried everything like using a different computer but nothing worked. I was aware that it must be a stupid mistake but I didn't expect this 😄
