### ISSUE TITLE
##Issue while executing georeferencing in shiny app

### ISSUE THREAD

**Issue by uniba99** [environmentalinformatics-marburg/distribution_digitizer_students#7]
**Warning**: _Error in py_call_impl: KeyError_: ***"None of [Index(['mapX', 'mapY', 'pixelX', 'pixelY', 'enable', 'dX', 'dY', 'residual'], dtype='object')] are in the [columns]"*** 
_[No stack trace available]_

**Comment by VenkateshMadhuvanthi** [comment]
Maybe try to manually remove the first two lines in the .points folder and execute the georeferencing module. This should work now :). The first line of the CSV file should start with "mapX', 'mapY', 'pixelX', 'pixelY', 'enable', 'dX', 'dY', 'residual'".
