### ISSUE TITLE
Issue while detecting maps (third step): created a huge output file (98GB)

### ISSUE THREAD

**Issue by Hallenbm** [environmentalinformatics-marburg/distribution_digitizer_students#8]
Hi,
while I was doing the third step in the Digitizer (Detect Maps, threshold 0.4), I stopped the process because R was still not finished after four hours and had already produced a data set amounting 98GB. I am very unsure how to handle such a large data set. Maybe I did something wrong in the previous step (I created like 15 map templates, maybe this was too much?) or is this normal and I should just run it until it´s done? 
Here is just a screenshot of the content of my output folder.

<img width="275" alt="Output_assignment4" src="https://user-images.githubusercontent.com/82364365/125037554-9258b200-e094-11eb-9ae1-9236450c71b0.png">

Thank you very much for comments/help!
Mona

**Comment by VenkateshMadhuvanthi** [comment]
Hi Hallen, 
Thank you very much for reporting the issue. Map Detection or Template Matching ends only when the last input file gets cross-correlated with the last template file. Hence, this might consume some time if you have a lot of input files. 15 Templates is good for the whole book. If the output maps are getting repeated (getting detected more than once), then for now manually filter the unwanted maps by deleting them. In summary, if you have 'm' input files and 'n' template files, then it would at least consume m*n seconds. Once, the process is done, you will get the message, "Successfully Executed".
Best Regards,
Madhu

**Comment by Hallenbm** [comment]
Hey Madhu, 
thank you for your reply. After 5 hours it finally came to the point "Successfully Executed". Now I have the problem, that I got this error message while doing the 4th step (filtering): Error in py_call_impl: OSError: [Errno 28] No space left on device
  [No stack trace available]. I think my ssd reached it´s limit (250GB). What should I do now? 
Kind regards,
Mona

**Comment by VenkateshMadhuvanthi** [comment]
Hi Mona, 
 Did you remove the repeated images?.

With regards,
Madhuvanthi V

**Comment by Hallenbm** [comment]
Hi Madhu, 
I which files count as "repeated files"? Here for example image 0027. 
<img width="814" alt="issue" src="https://user-images.githubusercontent.com/82364365/125184990-48053b80-e222-11eb-9c7a-709342c59588.png">
So I delete everything except 0027temp1_0 for example? If that´s the case, with so many images (40.000?) it would take a while to delete them manually; I have to think of a code line, that would do this for me.
Or do you mean the classification file? I´m a little bit lost..
Kind regards,
Mona

**Comment by VenkateshMadhuvanthi** [comment]
Yes, all these maps are from the same image on page 0027.

**Comment by Hallenbm** [comment]
Hmm okay, if there is no other solution for this, then I will delete them manually. This will take a while with 40.000 files..
Thank you for your help :)
