### ISSUE TITLE
Error message during Georeferencing

### ISSUE THREAD

**Issue by Hallenbm** [environmentalinformatics-marburg/distribution_digitizer_students#9]
Hey Madhu, 
now I´m at step 5th (Georeferencing) and I got this error message: Error in py_call_impl: KeyError: "None of [Index(['mapX', 'mapY', 'pixelX', 'pixelY', 'enable', 'dX', 'dY', 'residual'], dtype='object')] are in the [columns]"
  [No stack trace available]
I looked at the .points data and it looked like this:
<img width="385" alt="issue2" src="https://user-images.githubusercontent.com/82364365/125204842-7bc27e80-e27f-11eb-9b47-41ad3a53770c.png">
What could be the problem? I think I did everything as shown in the 12th session + deleting the duplicates.
Thank you for help/comments
Kind regards,
Mona

**Comment by VenkateshMadhuvanthi** [comment]
Remove the first line. The csv file should start with mapX, mapY........ etc. It should work now :)

**Comment by Hallenbm** [comment]
Thank you very much, it worked!
